### ISSUE TITLE
Cant load png images for trace 

### ISSUE THREAD

**Issue by meiry** [amuTBKT/Physics-Editor#3]
The png images are not loading 
when i select to load png image

**Comment by amuTBKT** [comment]
Yes, I am sorry but auto trace only supports 24-bit bitmap images as I've mentioned in the readme file
Basically there were some problems with cross-origin request when trying to extract pixel data using canvas, so I had to write a custom bitmap loader (read the binary image file and extract pixel data). And creating one for png image seemed like an overkill
